(* ::Package:: *)

(* ::Code::Initialization::Plain:: *)
(* Wolfram Language package *)

(* Author: ShungHong Li *)


(* ::Code::Initialization::Plain:: *)
Fourquarkmqq3::usage="Fourquarkmqq3[q_,{v1_,v2_,{a1_,b1_,c1_,d1_}},{v3_,v4_,{a2_,b2_,c2_,d2_}}] gives the third type \[LeftAngleBracket]\!\(\*OverscriptBox[\(\[Psi]\), \(_\)]\)G\[Psi]\!\(\*SuperscriptBox[\(\[RightAngleBracket]\), \(2\)]\)\[InvisibleComma] contribution of OPE result about <J1 J2>, with J1=\!\(\*SubscriptBox[OverscriptBox[\(\[CapitalPsi]\), \(_\)], \(a1\)]\)\!\(\*SubscriptBox[\(v1\[CapitalPsi]\), \(b1\)]\)\!\(\*SubscriptBox[OverscriptBox[\(\[CapitalPsi]\), \(_\)], \(c1\)]\)\!\(\*SubscriptBox[\(v2\[CapitalPsi]\), \(d1\)]\) and J2=\!\(\*SubscriptBox[OverscriptBox[\(\[CapitalPsi]\), \(_\)], \(b2\)]\)\!\(\*SubscriptBox[\(v3\[CapitalPsi]\), \(a2\)]\)\!\(\*SubscriptBox[OverscriptBox[\(\[CapitalPsi]\), \(_\)], \(d2\)]\)\!\(\*SubscriptBox[\(v4\[CapitalPsi]\), \(c2\)]\), here the background gluon comes from quark propatator. "

Fourquarkmqq3::inderr="Dummy indices conflict!"

Fourquarkmqq3::curerr="Unknow current structure!"



(* ::Code::Initialization::Plain:: *)
Begin["`Private`Fourquarkmqq3`"]


(* ::Code::Initialization::Plain:: *)
Options[Fourquarkmqq3] = {
	Parallelized->True,
	HoldFlavor->False,
	AutoNDR->True(*,
	ToD4->"Auto"*)
}


(* ::Code::Initialization::Plain:: *)
(* VS-first *)


(* ::Code::Initialization::Plain:: *)
(*------------------------------------------------------------------*)
(* propagators *)

(* xprop[x_]=(I^(1 - D)*DiracGamma[Momentum[x, D], D]*qGamma[D/2])/(2*Pi^(D/2)*Pair[Momentum[x, D], Momentum[x, D]]^(D/2));(*FourierPX[prop[q],{q,x}]*) *)

cqqm[x_,f_]=-1/4*1/CA + ((I/4)*DiracGamma[Momentum[x, D], D]*quarkMass[f])/(CA*D);

(*-----------------------------------*)
(* propagators and condensates *)

xprop[x_,f_]=(DiracGamma[Momentum[x, D], D]*qfact1[(I^(1 - D)*qGamma[D/2])/(2*Pi^(D/2))])/Pair[Momentum[x, D], Momentum[x, D]]^(D/2) + Pair[Momentum[x, D], Momentum[x, D]]^(1 - D/2)*qfact1[(I^(2 - D)*qGamma[-1 + D/2]*quarkMass[f])/(4*Pi^(D/2))];							


(* ::Code::Initialization::Plain:: *)
Fourquarkmqq3[qq_,{v1_,v2_,{a1_,b1_,c1_,d1_}},{v3_,v4_,{a2_,b2_,c2_,d2_}},OptionsPattern[]]:=Block[{null,tmp,tmp1,tmp2,hv3,hv4,holdf=OptionValue[HoldFlavor],atr,diagrams,fdir,pall,files,dot,setd},


(*--- check dummy indices in input ---*)
If[DummyCheck[v1,v2,v3,v4]==0,
	Message[Fourquarkmqq3::inderr];
	Abort[]
];


If[OptionValue[AutoNDR]===True,
	atr=TR5
	,
	atr=TR
];




(*If[OptionValue[ToD4]==="Auto"||OptionValue[ToD4]===4,
	setd=4
,
	setd=D
];
*)
(* B A^+ B *)
hv3=v3//ComplexConjugate;
hv4=v4//ComplexConjugate//FCI;
(* ComplexConjugate[sigma] will expand the DiracSigma to gamma matrices, recover it to DiracSigma *)
hv4=(hv4/.Dot->dot)/.(f1_ dot[aa___,DiracGamma[LorentzIndex[lor1_,dim___],dim___],DiracGamma[LorentzIndex[lor2_,dim___],dim___],bb___]+f2_ dot[aa___,DiracGamma[LorentzIndex[lor2_,dim___],dim___],DiracGamma[LorentzIndex[lor1_,dim___],dim___],bb___])/;(f1+f2===0):>-2I f1 dot[aa,DiracSigma[DiracGamma[LorentzIndex[lor1,dim],dim],DiracGamma[LorentzIndex[lor2,dim],dim]],bb];
hv4=hv4/. {null->1,dot->Dot};


diagrams={xtype1,xtype2,xtype3,xtype4,xtype5,xtype6};

(*--------------------------------------------*)		

					
If[DirectoryQ[OptionValue[Parallelized]//ToString],
	fdir=OptionValue[Parallelized];
	pall="External"
,
	fdir="None";
	pall=OptionValue[Parallelized]
];	


(*---------------------------------------------------*)
If[pall===True,

	DistributeDefinitions[qq,v1,v2,a1,b1,c1,d1,a2,b2,c2,d2];
	
	tmp=Plus@@WaitAll[ParallelSubmit[{hv3,hv4,holdf,atr},#[qq,{v1,v2,{a1,b1,c1,d1}},{hv3,hv4,{a2,b2,c2,d2}},holdf,atr]]&/@diagrams];
	QGather[(tmp/.{CA->SUNN,CF->(SUNN^2 - 1)/(2SUNN)})//Expand//SUNSimplify,qq,ShowasTable->False]/.CA-2CF->1/CA
	
,

	If[pall==="External",
	
		DistributeDefinitions[qq,v1,v2,a1,b1,c1,d1,a2,b2,c2,d2];
		
		If[fdir==="None",
		
			ParallelSubmit[{hv3,hv4,holdf,atr},#[qq,{v1,v2,{a1,b1,c1,d1}},{hv3,hv4,{a2,b2,c2,d2}},holdf,atr]]&/@diagrams
		,
		
			files=(StringSplit[ToString[#],"`"][[-1]])&/@diagrams;
			files=("Fourquarkmqq3_"<>#)&/@files;
			
			ImExport[fdir,
					files,
					{{hv3,hv4,holdf,atr},
					{qq,{v1,v2,{a1,b1,c1,d1}},{hv3,hv4,{a2,b2,c2,d2}},holdf,atr},
					diagrams}
					]
		]
		(* !!! do not touch tmp before WaitAll[tmp], any function may modifiy the things in EvaluationObject[...] should not be used here. !!! *)
	,
	
	
		tmp=Plus@@Map[#[qq,{v1,v2,{a1,b1,c1,d1}},{hv3,hv4,{a2,b2,c2,d2}},holdf,atr]&,diagrams];
		QGather[(tmp/.{CA->SUNN,CF->(SUNN^2 - 1)/(2SUNN)})//Expand//SUNSimplify,qq,ShowasTable->False]/.CA-2CF->1/CA
	]
]

]



(* ::Code::Initialization::Plain:: *)
(*--- The following are generated by algorithm ---*)


(* ::Input::Initialization::Plain:: *)
xtype1[qq_,{v1_,v2_,{a1_,b1_,c1_,d1_}},{hv3_,hv4_,{a2_,b2_,c2_,d2_}},holdf_,atr_]:=Block[{x,q,dia1,lor1,lor2,lora,lorb,sun,sun1,sun2,tr,str,contract,dot},


 dia1=Condensate[{a1, d1}]*Condensate[{b2, b1}]*Condensate[{d2, c2}]*contract[tr[str[dot[hv4, cqqm[0, c2]]]]*tr[str[dot[v2, cqqm[0, d1], v1, cqqm[x, b1], hv3, xprop[-x, a2]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, b2]*FlavorDelta[c2, d2]*FlavorDelta[d1, a1] - Condensate[{b2, d1}]*Condensate[{c1, b1}]*Condensate[{d2, a2}]*contract[tr[str[dot[hv4, xprop[-x, c2], v1, cqqm[0, b1], v2, cqqm[x, d1], hv3, cqqm[0, a2]]]]]*FlavorDelta[a2, d2]*FlavorDelta[b1, c1]*FlavorDelta[c2, a1]*FlavorDelta[d1, b2] - Condensate[{a1, b1}]*Condensate[{b2, d1}]*Condensate[{d2, c2}]*contract[tr[str[dot[hv4, cqqm[0, c2]]]]*tr[str[dot[v1, cqqm[0, b1]]]]*tr[str[dot[hv3, xprop[-x, a2], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, a1]*FlavorDelta[c2, d2]*FlavorDelta[d1, b2] + Condensate[{b2, d1}]*Condensate[{c1, b1}]*Condensate[{d2, c2}]*contract[tr[str[dot[hv4, cqqm[0, c2]]]]*tr[str[dot[hv3, xprop[-x, a2], v1, cqqm[0, b1], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, c1]*FlavorDelta[c2, d2]*FlavorDelta[d1, b2] + Condensate[{b2, b1}]*Condensate[{c1, d1}]*Condensate[{d2, a2}]*contract[tr[str[dot[v2, cqqm[0, d1]]]]*tr[str[dot[hv4, xprop[-x, c2], v1, cqqm[x, b1], hv3, cqqm[0, a2]]]]]*FlavorDelta[a2, d2]*FlavorDelta[b1, b2]*FlavorDelta[c2, a1]*FlavorDelta[d1, c1] - Condensate[{b2, b1}]*Condensate[{c1, d1}]*Condensate[{d2, c2}]*contract[tr[str[dot[hv4, cqqm[0, c2]]]]*tr[str[dot[v2, cqqm[0, d1]]]]*tr[str[dot[hv3, xprop[-x, a2], v1, cqqm[x, b1]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, b2]*FlavorDelta[c2, d2]*FlavorDelta[d1, c1] + Condensate[{b2, a2}]*Condensate[{c1, b1}]*Condensate[{d2, d1}]*contract[tr[str[dot[hv3, cqqm[0, a2]]]]*tr[str[dot[hv4, xprop[-x, c2], v1, cqqm[0, b1], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, b2]*FlavorDelta[b1, c1]*FlavorDelta[c2, a1]*FlavorDelta[d1, d2] - Condensate[{a1, b1}]*Condensate[{b2, a2}]*Condensate[{d2, d1}]*contract[tr[str[dot[hv3, cqqm[0, a2]]]]*tr[str[dot[v1, cqqm[0, b1]]]]*tr[str[dot[hv4, xprop[-x, c2], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, b2]*FlavorDelta[b1, a1]*FlavorDelta[c2, c1]*FlavorDelta[d1, d2];


 dia1=dia1/.{FlavorDelta[fa_,fb_,___]:>FlavorDelta[fa,fb,HoldFlavor->holdf],dot[aa___,1,bb___]:>dot[aa,bb]}/.dot->Dot/.str->SUNTrace/.{tr->atr,contract->Contract}/.sunSimplify->SUNSimplify;


 dia1=FourierXP[Expand[dia1]/.{Power[_quarkMass, n_]->0, mm1_quarkMass mm2_quarkMass->0},{x,q}];


 dia1=QEvaluate[I ScaleMu^(1(4-D)) dia1,q,HoldFlavor->holdf,Parallelized->False]/.q->qq/.CA-2CF->1/CA/.{-1+CA^2-2CA CF->0,1-CA^2+2CA CF->0}/.CF->(CA^2-1)/(2CA)


]


(* ::Input::Initialization::Plain:: *)
xtype2[qq_,{v1_,v2_,{a1_,b1_,c1_,d1_}},{hv3_,hv4_,{a2_,b2_,c2_,d2_}},holdf_,atr_]:=Block[{x,q,dia2,lor1,lor2,lora,lorb,sun,sun1,sun2,tr,str,contract,dot},


 dia2=-(Condensate[{a1, d1}]*Condensate[{b2, c2}]*Condensate[{c1, a2}]*contract[tr[str[dot[hv3, cqqm[-x, a2], v2, cqqm[0, d1], v1, xprop[x, b1], hv4, cqqm[0, c2]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, d2]*FlavorDelta[c2, b2]*FlavorDelta[d1, a1]) - Condensate[{a1, d1}]*Condensate[{c1, c2}]*Condensate[{d2, a2}]*contract[tr[str[dot[hv4, cqqm[-x, c2], v2, cqqm[0, d1], v1, xprop[x, b1], hv3, cqqm[0, a2]]]]]*FlavorDelta[a2, d2]*FlavorDelta[b1, b2]*FlavorDelta[c2, c1]*FlavorDelta[d1, a1] + Condensate[{a1, c2}]*Condensate[{c1, a2}]*Condensate[{d2, b1}]*contract[tr[str[dot[hv3, cqqm[-x, a2], v2, xprop[x, d1]]]]*tr[str[dot[hv4, cqqm[-x, c2], v1, cqqm[x, b1]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, d2]*FlavorDelta[c2, a1]*FlavorDelta[d1, b2] + Condensate[{a1, c2}]*Condensate[{b2, d1}]*Condensate[{d2, b1}]*contract[tr[str[dot[hv3, xprop[-x, a2], v2, cqqm[x, d1]]]]*tr[str[dot[hv4, cqqm[-x, c2], v1, cqqm[x, b1]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, d2]*FlavorDelta[c2, a1]*FlavorDelta[d1, b2] - Condensate[{a1, a2}]*Condensate[{c1, d1}]*Condensate[{d2, c2}]*contract[tr[str[dot[hv4, cqqm[0, c2]]]]*tr[str[dot[v2, cqqm[0, d1]]]]*tr[str[dot[hv3, cqqm[-x, a2], v1, xprop[x, b1]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, b2]*FlavorDelta[c2, d2]*FlavorDelta[d1, c1] - Condensate[{a1, c2}]*Condensate[{b2, b1}]*Condensate[{c1, a2}]*contract[tr[str[dot[hv4, cqqm[-x, c2], v1, cqqm[x, b1], hv3, cqqm[-x, a2], v2, xprop[x, d1]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, b2]*FlavorDelta[c2, a1]*FlavorDelta[d1, d2] + Condensate[{a1, b1}]*Condensate[{b2, c2}]*Condensate[{d2, d1}]*contract[tr[str[dot[v1, cqqm[0, b1]]]]*tr[str[dot[hv3, xprop[-x, a2], v2, cqqm[x, d1], hv4, cqqm[0, c2]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, a1]*FlavorDelta[c2, b2]*FlavorDelta[d1, d2] + Condensate[{a1, a2}]*Condensate[{b2, b1}]*Condensate[{c1, c2}]*contract[tr[str[dot[hv3, cqqm[-x, a2], v1, cqqm[x, b1]]]]*tr[str[dot[hv4, cqqm[-x, c2], v2, xprop[x, d1]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, b2]*FlavorDelta[c2, c1]*FlavorDelta[d1, d2];


 dia2=dia2/.{FlavorDelta[fa_,fb_,___]:>FlavorDelta[fa,fb,HoldFlavor->holdf],dot[aa___,1,bb___]:>dot[aa,bb]}/.dot->Dot/.str->SUNTrace/.{tr->atr,contract->Contract}/.sunSimplify->SUNSimplify;


 dia2=FourierXP[Expand[dia2]/.{Power[_quarkMass, n_]->0, mm1_quarkMass mm2_quarkMass->0},{x,q}];


 dia2=QEvaluate[I ScaleMu^(1(4-D)) dia2,q,HoldFlavor->holdf,Parallelized->False]/.q->qq/.CA-2CF->1/CA/.{-1+CA^2-2CA CF->0,1-CA^2+2CA CF->0}/.CF->(CA^2-1)/(2CA)


]


(* ::Input::Initialization::Plain:: *)
xtype3[qq_,{v1_,v2_,{a1_,b1_,c1_,d1_}},{hv3_,hv4_,{a2_,b2_,c2_,d2_}},holdf_,atr_]:=Block[{x,q,dia3,lor1,lor2,lora,lorb,sun,sun1,sun2,tr,str,contract,dot},


 dia3=Condensate[{a1, b1}]*Condensate[{c1, c2}]*Condensate[{d2, a2}]*contract[tr[str[dot[v1, cqqm[0, b1]]]]*tr[str[dot[hv4, cqqm[-x, c2], v2, xprop[x, d1], hv3, cqqm[0, a2]]]]]*FlavorDelta[a2, d2]*FlavorDelta[b1, a1]*FlavorDelta[c2, c1]*FlavorDelta[d1, b2] - Condensate[{a1, a2}]*Condensate[{c1, c2}]*Condensate[{d2, b1}]*contract[tr[str[dot[hv3, cqqm[-x, a2], v1, cqqm[x, b1], hv4, cqqm[-x, c2], v2, xprop[x, d1]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, d2]*FlavorDelta[c2, c1]*FlavorDelta[d1, b2] - Condensate[{a1, a2}]*Condensate[{b2, d1}]*Condensate[{d2, b1}]*contract[tr[str[dot[hv3, cqqm[-x, a2], v1, cqqm[x, b1], hv4, xprop[-x, c2], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, d2]*FlavorDelta[c2, c1]*FlavorDelta[d1, b2] - Condensate[{a1, a2}]*Condensate[{b2, d1}]*Condensate[{c1, c2}]*contract[tr[str[dot[hv3, cqqm[-x, a2], v1, xprop[x, b1], hv4, cqqm[-x, c2], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, d2]*FlavorDelta[c2, c1]*FlavorDelta[d1, b2] - Condensate[{b2, d1}]*Condensate[{c1, c2}]*Condensate[{d2, b1}]*contract[tr[str[dot[hv3, xprop[-x, a2], v1, cqqm[x, b1], hv4, cqqm[-x, c2], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, d2]*FlavorDelta[c2, c1]*FlavorDelta[d1, b2] - Condensate[{a1, c2}]*Condensate[{b2, a2}]*Condensate[{c1, d1}]*contract[tr[str[dot[hv3, cqqm[0, a2]]]]*tr[str[dot[v2, cqqm[0, d1]]]]*tr[str[dot[hv4, cqqm[-x, c2], v1, xprop[x, b1]]]]]*FlavorDelta[a2, b2]*FlavorDelta[b1, d2]*FlavorDelta[c2, a1]*FlavorDelta[d1, c1] + Condensate[{a1, a2}]*Condensate[{b2, c2}]*Condensate[{c1, d1}]*contract[tr[str[dot[v2, cqqm[0, d1]]]]*tr[str[dot[hv3, cqqm[-x, a2], v1, xprop[x, b1], hv4, cqqm[0, c2]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, d2]*FlavorDelta[c2, b2]*FlavorDelta[d1, c1] + Condensate[{a1, a2}]*Condensate[{c1, c2}]*Condensate[{d2, d1}]*contract[tr[str[dot[hv3, cqqm[-x, a2], v1, xprop[x, b1]]]]*tr[str[dot[hv4, cqqm[-x, c2], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, b2]*FlavorDelta[c2, c1]*FlavorDelta[d1, d2];


 dia3=dia3/.{FlavorDelta[fa_,fb_,___]:>FlavorDelta[fa,fb,HoldFlavor->holdf],dot[aa___,1,bb___]:>dot[aa,bb]}/.dot->Dot/.str->SUNTrace/.{tr->atr,contract->Contract}/.sunSimplify->SUNSimplify;


 dia3=FourierXP[Expand[dia3]/.{Power[_quarkMass, n_]->0, mm1_quarkMass mm2_quarkMass->0},{x,q}];


 dia3=QEvaluate[I ScaleMu^(1(4-D)) dia3,q,HoldFlavor->holdf,Parallelized->False]/.q->qq/.CA-2CF->1/CA/.{-1+CA^2-2CA CF->0,1-CA^2+2CA CF->0}/.CF->(CA^2-1)/(2CA)


]


(* ::Input::Initialization::Plain:: *)
xtype4[qq_,{v1_,v2_,{a1_,b1_,c1_,d1_}},{hv3_,hv4_,{a2_,b2_,c2_,d2_}},holdf_,atr_]:=Block[{x,q,dia4,lor1,lor2,lora,lorb,sun,sun1,sun2,tr,str,contract,dot},


 dia4=-(Condensate[{a1, d1}]*Condensate[{b2, c2}]*Condensate[{d2, b1}]*contract[tr[str[dot[hv3, xprop[-x, a2], v2, cqqm[0, d1], v1, cqqm[x, b1], hv4, cqqm[0, c2]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, d2]*FlavorDelta[c2, b2]*FlavorDelta[d1, a1]) - Condensate[{a1, c2}]*Condensate[{c1, b1}]*Condensate[{d2, a2}]*contract[tr[str[dot[hv4, cqqm[-x, c2], v1, cqqm[0, b1], v2, xprop[x, d1], hv3, cqqm[0, a2]]]]]*FlavorDelta[a2, d2]*FlavorDelta[b1, c1]*FlavorDelta[c2, a1]*FlavorDelta[d1, b2] + Condensate[{b2, d1}]*Condensate[{c1, a2}]*Condensate[{d2, b1}]*contract[tr[str[dot[hv3, cqqm[-x, a2], v2, cqqm[x, d1]]]]*tr[str[dot[hv4, xprop[-x, c2], v1, cqqm[x, b1]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, d2]*FlavorDelta[c2, a1]*FlavorDelta[d1, b2] - Condensate[{a1, b1}]*Condensate[{c1, a2}]*Condensate[{d2, c2}]*contract[tr[str[dot[hv4, cqqm[0, c2]]]]*tr[str[dot[v1, cqqm[0, b1]]]]*tr[str[dot[hv3, cqqm[-x, a2], v2, xprop[x, d1]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, a1]*FlavorDelta[c2, d2]*FlavorDelta[d1, b2] + Condensate[{a1, c2}]*Condensate[{c1, d1}]*Condensate[{d2, a2}]*contract[tr[str[dot[v2, cqqm[0, d1]]]]*tr[str[dot[hv4, cqqm[-x, c2], v1, xprop[x, b1], hv3, cqqm[0, a2]]]]]*FlavorDelta[a2, d2]*FlavorDelta[b1, b2]*FlavorDelta[c2, a1]*FlavorDelta[d1, c1] - Condensate[{b2, a2}]*Condensate[{c1, d1}]*Condensate[{d2, b1}]*contract[tr[str[dot[hv3, cqqm[0, a2]]]]*tr[str[dot[v2, cqqm[0, d1]]]]*tr[str[dot[hv4, xprop[-x, c2], v1, cqqm[x, b1]]]]]*FlavorDelta[a2, b2]*FlavorDelta[b1, d2]*FlavorDelta[c2, a1]*FlavorDelta[d1, c1] - Condensate[{a1, a2}]*Condensate[{b2, c2}]*Condensate[{c1, b1}]*contract[tr[str[dot[hv3, cqqm[-x, a2], v1, cqqm[0, b1], v2, xprop[x, d1], hv4, cqqm[0, c2]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, c1]*FlavorDelta[c2, b2]*FlavorDelta[d1, d2] + Condensate[{a1, a2}]*Condensate[{b2, b1}]*Condensate[{d2, d1}]*contract[tr[str[dot[hv3, cqqm[-x, a2], v1, cqqm[x, b1]]]]*tr[str[dot[hv4, xprop[-x, c2], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, b2]*FlavorDelta[c2, c1]*FlavorDelta[d1, d2];


 dia4=dia4/.{FlavorDelta[fa_,fb_,___]:>FlavorDelta[fa,fb,HoldFlavor->holdf],dot[aa___,1,bb___]:>dot[aa,bb]}/.dot->Dot/.str->SUNTrace/.{tr->atr,contract->Contract}/.sunSimplify->SUNSimplify;


 dia4=FourierXP[Expand[dia4]/.{Power[_quarkMass, n_]->0, mm1_quarkMass mm2_quarkMass->0},{x,q}];


 dia4=QEvaluate[I ScaleMu^(1(4-D)) dia4,q,HoldFlavor->holdf,Parallelized->False]/.q->qq/.CA-2CF->1/CA/.{-1+CA^2-2CA CF->0,1-CA^2+2CA CF->0}/.CF->(CA^2-1)/(2CA)


]


(* ::Input::Initialization::Plain:: *)
xtype5[qq_,{v1_,v2_,{a1_,b1_,c1_,d1_}},{hv3_,hv4_,{a2_,b2_,c2_,d2_}},holdf_,atr_]:=Block[{x,q,dia5,lor1,lor2,lora,lorb,sun,sun1,sun2,tr,str,contract,dot},


 dia5=-(Condensate[{a1, d1}]*Condensate[{b2, b1}]*Condensate[{d2, a2}]*contract[tr[str[dot[hv4, xprop[-x, c2], v2, cqqm[0, d1], v1, cqqm[x, b1], hv3, cqqm[0, a2]]]]]*FlavorDelta[a2, d2]*FlavorDelta[b1, b2]*FlavorDelta[c2, c1]*FlavorDelta[d1, a1]) + Condensate[{a1, d1}]*Condensate[{b2, a2}]*Condensate[{c1, c2}]*contract[tr[str[dot[hv3, cqqm[0, a2]]]]*tr[str[dot[v2, cqqm[0, d1], v1, xprop[x, b1], hv4, cqqm[-x, c2]]]]]*FlavorDelta[a2, b2]*FlavorDelta[b1, d2]*FlavorDelta[c2, c1]*FlavorDelta[d1, a1] + Condensate[{a1, a2}]*Condensate[{c1, b1}]*Condensate[{d2, c2}]*contract[tr[str[dot[hv4, cqqm[0, c2]]]]*tr[str[dot[hv3, cqqm[-x, a2], v1, cqqm[0, b1], v2, xprop[x, d1]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, c1]*FlavorDelta[c2, d2]*FlavorDelta[d1, b2] - Condensate[{a1, c2}]*Condensate[{b2, b1}]*Condensate[{d2, d1}]*contract[tr[str[dot[hv4, cqqm[-x, c2], v1, cqqm[x, b1], hv3, xprop[-x, a2], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, b2]*FlavorDelta[c2, a1]*FlavorDelta[d1, d2] - Condensate[{b2, b1}]*Condensate[{c1, a2}]*Condensate[{d2, d1}]*contract[tr[str[dot[hv4, xprop[-x, c2], v1, cqqm[x, b1], hv3, cqqm[-x, a2], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, b2]*FlavorDelta[c2, a1]*FlavorDelta[d1, d2] + Condensate[{a1, c2}]*Condensate[{b2, a2}]*Condensate[{c1, b1}]*contract[tr[str[dot[hv3, cqqm[0, a2]]]]*tr[str[dot[hv4, cqqm[-x, c2], v1, cqqm[0, b1], v2, xprop[x, d1]]]]]*FlavorDelta[a2, b2]*FlavorDelta[b1, c1]*FlavorDelta[c2, a1]*FlavorDelta[d1, d2] - Condensate[{b2, c2}]*Condensate[{c1, b1}]*Condensate[{d2, d1}]*contract[tr[str[dot[hv3, xprop[-x, a2], v1, cqqm[0, b1], v2, cqqm[x, d1], hv4, cqqm[0, c2]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, c1]*FlavorDelta[c2, b2]*FlavorDelta[d1, d2] - Condensate[{a1, b1}]*Condensate[{b2, a2}]*Condensate[{c1, c2}]*contract[tr[str[dot[hv3, cqqm[0, a2]]]]*tr[str[dot[v1, cqqm[0, b1]]]]*tr[str[dot[hv4, cqqm[-x, c2], v2, xprop[x, d1]]]]]*FlavorDelta[a2, b2]*FlavorDelta[b1, a1]*FlavorDelta[c2, c1]*FlavorDelta[d1, d2];


 dia5=dia5/.{FlavorDelta[fa_,fb_,___]:>FlavorDelta[fa,fb,HoldFlavor->holdf],dot[aa___,1,bb___]:>dot[aa,bb]}/.dot->Dot/.str->SUNTrace/.{tr->atr,contract->Contract}/.sunSimplify->SUNSimplify;


 dia5=FourierXP[Expand[dia5]/.{Power[_quarkMass, n_]->0, mm1_quarkMass mm2_quarkMass->0},{x,q}];


 dia5=QEvaluate[I ScaleMu^(1(4-D)) dia5,q,HoldFlavor->holdf,Parallelized->False]/.q->qq/.CA-2CF->1/CA/.{-1+CA^2-2CA CF->0,1-CA^2+2CA CF->0}/.CF->(CA^2-1)/(2CA)


]


(* ::Input::Initialization::Plain:: *)
xtype6[qq_,{v1_,v2_,{a1_,b1_,c1_,d1_}},{hv3_,hv4_,{a2_,b2_,c2_,d2_}},holdf_,atr_]:=Block[{x,q,dia6,lor1,lor2,lora,lorb,sun,sun1,sun2,tr,str,contract,dot},


 dia6=Condensate[{a1, d1}]*Condensate[{b2, a2}]*Condensate[{d2, b1}]*contract[tr[str[dot[hv3, cqqm[0, a2]]]]*tr[str[dot[v2, cqqm[0, d1], v1, cqqm[x, b1], hv4, xprop[-x, c2]]]]]*FlavorDelta[a2, b2]*FlavorDelta[b1, d2]*FlavorDelta[c2, c1]*FlavorDelta[d1, a1] + Condensate[{a1, d1}]*Condensate[{c1, a2}]*Condensate[{d2, c2}]*contract[tr[str[dot[hv4, cqqm[0, c2]]]]*tr[str[dot[v2, cqqm[0, d1], v1, xprop[x, b1], hv3, cqqm[-x, a2]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, b2]*FlavorDelta[c2, d2]*FlavorDelta[d1, a1] + Condensate[{a1, c2}]*Condensate[{b2, d1}]*Condensate[{c1, a2}]*contract[tr[str[dot[hv3, cqqm[-x, a2], v2, cqqm[x, d1]]]]*tr[str[dot[hv4, cqqm[-x, c2], v1, xprop[x, b1]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, d2]*FlavorDelta[c2, a1]*FlavorDelta[d1, b2] + Condensate[{a1, b1}]*Condensate[{b2, d1}]*Condensate[{d2, a2}]*contract[tr[str[dot[v1, cqqm[0, b1]]]]*tr[str[dot[hv4, xprop[-x, c2], v2, cqqm[x, d1], hv3, cqqm[0, a2]]]]]*FlavorDelta[a2, d2]*FlavorDelta[b1, a1]*FlavorDelta[c2, c1]*FlavorDelta[d1, b2] + Condensate[{b2, c2}]*Condensate[{c1, d1}]*Condensate[{d2, b1}]*contract[tr[str[dot[v2, cqqm[0, d1]]]]*tr[str[dot[hv3, xprop[-x, a2], v1, cqqm[x, b1], hv4, cqqm[0, c2]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, d2]*FlavorDelta[c2, b2]*FlavorDelta[d1, c1] - Condensate[{a1, c2}]*Condensate[{c1, a2}]*Condensate[{d2, d1}]*contract[tr[str[dot[hv4, cqqm[-x, c2], v1, xprop[x, b1], hv3, cqqm[-x, a2], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, b2]*FlavorDelta[c2, a1]*FlavorDelta[d1, d2] + Condensate[{a1, b1}]*Condensate[{b2, c2}]*Condensate[{c1, a2}]*contract[tr[str[dot[v1, cqqm[0, b1]]]]*tr[str[dot[hv3, cqqm[-x, a2], v2, xprop[x, d1], hv4, cqqm[0, c2]]]]]*FlavorDelta[a2, c1]*FlavorDelta[b1, a1]*FlavorDelta[c2, b2]*FlavorDelta[d1, d2] + Condensate[{b2, b1}]*Condensate[{c1, c2}]*Condensate[{d2, d1}]*contract[tr[str[dot[hv3, xprop[-x, a2], v1, cqqm[x, b1]]]]*tr[str[dot[hv4, cqqm[-x, c2], v2, cqqm[x, d1]]]]]*FlavorDelta[a2, a1]*FlavorDelta[b1, b2]*FlavorDelta[c2, c1]*FlavorDelta[d1, d2];


 dia6=dia6/.{FlavorDelta[fa_,fb_,___]:>FlavorDelta[fa,fb,HoldFlavor->holdf],dot[aa___,1,bb___]:>dot[aa,bb]}/.dot->Dot/.str->SUNTrace/.{tr->atr,contract->Contract}/.sunSimplify->SUNSimplify;


 dia6=FourierXP[Expand[dia6]/.{Power[_quarkMass, n_]->0, mm1_quarkMass mm2_quarkMass->0},{x,q}];


 dia6=QEvaluate[I ScaleMu^(1(4-D)) dia6,q,HoldFlavor->holdf,Parallelized->False]/.q->qq/.CA-2CF->1/CA/.{-1+CA^2-2CA CF->0,1-CA^2+2CA CF->0}/.CF->(CA^2-1)/(2CA)


]


(* ::Code::Initialization::Plain:: *)
End[]
(*EndPackage[]*)
